Vagrant::Config.run do |config|
  config.vm.box = "mediawiki"
  config.vm.provision :shell, :inline => 'sed -i "s/#prepend domain-name-servers 127.0.0.1/prepend domain-name-servers 8.8.8.8/g" /etc/dhcp/dhclient.conf && service networking start; gem list | grep chef || gem install chef --no-rdoc --no-ri; apt-get -y update'
  config.vm.forward_port 80, 8888
  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug
    chef.json.merge!(JSON.parse(File.read(File.join(Dir.pwd, 'node.json'))))
    chef.run_list = [ "recipe[mediawiki_application]" ]
  end
end